### ISSUE TITLE
Better overview

### ISSUE THREAD

**Issue by michakrapp** [cookiefactory/handbook#1]
For a better overview directly up front over the handbook, we should

a) move the TOC content into the README
or
b) link the TOC page in the README

I would prefer a) and can do it

**Comment by raphbibus** [comment]
The plan is to deploy the handbook with https://rust-lang.github.io/mdBook/index.html on handbook.thomann.io or a similar subdomain. Therefore the structure needs to be changed according to the specs of mdBook.

**Comment by raphbibus** [comment]
The structure is changed for mdBook now. Ops team takes care of subdomain deployment in SYS-3190. Feel free to follow the ticket in Jira. Will close the issue.
